name: pyviz
channels:
  - conda-forge
dependencies:
  - colorcet
  - fastparquet
  - flake8
  - intake
  - intake-parquet
  - jinja2
  - m2r
  - markdown
  - pyviz::nbsite
  - pyviz::nbsmoke
  - pyviz::pyctdev
  - pytest
  - pyyaml
  - requests
  - tornado<6
